"""initial migration

Revision ID: b505c25f41d4
Revises: 
Create Date: 2026-02-11 18:29:57.753367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b505c25f41d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('continent', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('startYear', sa.Integer(), nullable=False),
    sa.Column('endYear', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('parentId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parentId'], ['events.id'], name='parentIDName'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('association_table',
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('events_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], name='countryIDKey'),
    sa.ForeignKeyConstraint(['events_id'], ['events.id'], name='eventIDKey'),
    sa.PrimaryKeyConstraint('country_id', 'events_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association_table')
    op.drop_table('events')
    op.drop_table('country')
    # ### end Alembic commands ###
