"""initial

Revision ID: ebea17fb1e59
Revises: 
Create Date: 2026-02-25 12:51:09.283074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebea17fb1e59'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('continent', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('start', sa.Date(), nullable=False),
    sa.Column('end', sa.Date(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('theme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('association_table',
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('country_id', 'event_id')
    )
    op.create_table('events_table',
    sa.Column('parent_event', sa.Integer(), nullable=False),
    sa.Column('child_event', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['child_event'], ['event.id'], ),
    sa.ForeignKeyConstraint(['parent_event'], ['event.id'], ),
    sa.PrimaryKeyConstraint('parent_event', 'child_event')
    )
    op.create_table('themes_table',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('themes_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['themes_id'], ['theme.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'themes_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('themes_table')
    op.drop_table('events_table')
    op.drop_table('association_table')
    op.drop_table('theme')
    op.drop_table('event')
    op.drop_table('country')
    # ### end Alembic commands ###
